/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Domio
 * The domio property application
 * OpenAPI spec version: 1.0
 */
export interface SignInData {
  email: string;
  password: string;
}

export interface AuthToken {
  access_token: string;
}

export interface SignupDto { [key: string]: unknown }

export interface IGetSession {
  sessionToken: string;
  userId: string;
  expires: string;
}

export interface GetSessionRole {
  name: string;
  description: string;
  id: number;
  createdAt: string;
}

export interface GetSessionUserWithRoles {
  id: string;
  email: string;
  emailVerified: string;
  name: string;
  image: string;
  roles: GetSessionRole[];
}

export interface GetSessionAndUserResult {
  session: IGetSession;
  user: GetSessionUserWithRoles;
}

