/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Domio
 * The domio property application
 * OpenAPI spec version: 1.0
 */
import { customInstanceMutator } from '../httpclient';
export interface SignInData {
  email: string;
  password: string;
}

export interface AuthToken {
  access_token: string;
}

export interface SignupDto {
  name: string;
  email: string;
  /**
   * @minLength 8
   * @maxLength 20
   */
  password: string;
}

export interface IGetSession {
  sessionToken: string;
  userId: string;
  expires: string;
}

export interface GetSessionRole {
  name: string;
  description: string;
  id: number;
  createdAt: string;
}

export interface GetSessionUserWithRoles {
  id: string;
  email: string;
  emailVerified: string;
  name: string;
  image: string;
  roles: GetSessionRole[];
}

export interface GetSessionAndUserResult {
  session: IGetSession;
  user: GetSessionUserWithRoles;
}

export type CreatePropertyDtoType =
  (typeof CreatePropertyDtoType)[keyof typeof CreatePropertyDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePropertyDtoType = {
  house: 'house',
  apartment: 'apartment',
  townhouse: 'townhouse',
  condo: 'condo',
  duplex: 'duplex',
  commercial: 'commercial',
  land: 'land',
} as const;

export interface CreatePropertyDto {
  type: CreatePropertyDtoType;
  name: string;
  streetName: string;
  streetNumber: number;
  suburb: string;
  country: string;
  bedrooms: number;
  lon: string;
  lat: string;
  bathrooms: number;
  hasParking: boolean;
  isFurnished: boolean;
  ownerId: string;
  isForRent: boolean;
  isForSale: boolean;
  images: string[];
  isActive: boolean;
  description?: string;
  address?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  squareFeet?: number;
  price?: number;
  mainImage?: string;
}

export type UpdatePropertyDtoType =
  (typeof UpdatePropertyDtoType)[keyof typeof UpdatePropertyDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePropertyDtoType = {
  house: 'house',
  apartment: 'apartment',
  townhouse: 'townhouse',
  condo: 'condo',
  duplex: 'duplex',
  commercial: 'commercial',
  land: 'land',
} as const;

export interface UpdatePropertyDto {
  type: UpdatePropertyDtoType;
  name: string;
  streetName: string;
  streetNumber: number;
  suburb: string;
  country: string;
  bedrooms: number;
  bathrooms: number;
  hasParking: boolean;
  isFurnished: boolean;
  ownerId: string;
  isForRent: boolean;
  isForSale: boolean;
  images: string[];
  isActive: boolean;
  description?: string;
  address?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  squareFeet?: number;
  lat: string;
  lon: string;
  price?: number;
  mainImage?: string;
  id: string;
}

export interface UpdatePropertyResult {
  type: string;
  name: string;
  streetName: string;
  streetNumber: number;
  lat: string;
  lon: string;
  suburb: string;
  country: string;
  bedrooms: number;
  bathrooms: number;
  hasParking: boolean;
  isFurnished: boolean;
  isForRent: boolean;
  isForSale: boolean;
  images: string[];
  isActive: boolean;
  description?: string;
  address?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  squareFeet?: number;
  price?: number;
  mainImage?: string;
}

export type PropertyResultType =
  (typeof PropertyResultType)[keyof typeof PropertyResultType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PropertyResultType = {
  house: 'house',
  apartment: 'apartment',
  townhouse: 'townhouse',
  condo: 'condo',
  duplex: 'duplex',
  commercial: 'commercial',
  land: 'land',
} as const;

export interface PropertyResult {
  id: string;
  type: PropertyResultType;
  name: string;
  streetName: string;
  streetNumber: number;
  suburb: string;
  country: string;
  bedrooms: number;
  bathrooms: number;
  hasParking: boolean;
  isFurnished: boolean;
  ownerId: string;
  isForRent: boolean;
  isForSale: boolean;
  images: string[];
  isActive: boolean;
  description?: string;
  lat: string;
  lon: string;
  address?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  squareFeet?: number;
  price?: number;
  mainImage?: string;
}

export interface PropertyStatsResult {
  userId: string;
  userName: string;
  totalProperties: number;
  propertiesAvailable: number;
  propertiesRented: number;
  portfolioValue: number;
}

export type UploadFileDtoFolder =
  (typeof UploadFileDtoFolder)[keyof typeof UploadFileDtoFolder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadFileDtoFolder = {
  properties: 'properties',
  users: 'users',
  tenancies: 'tenancies',
  payments: 'payments',
} as const;

export type UploadFileDtoSub =
  (typeof UploadFileDtoSub)[keyof typeof UploadFileDtoSub];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadFileDtoSub = {
  images: 'images',
  documents: 'documents',
  profile: 'profile',
  identity: 'identity',
  agreements: 'agreements',
  inspections: 'inspections',
  proof: 'proof',
} as const;

export interface UploadFileDto {
  file: Blob;
  folder: UploadFileDtoFolder;
  sub: UploadFileDtoSub;
  tenantId: string;
  propertyId?: string;
  userId?: string;
  tenancyId?: string;
  paymentId?: string;
  fileName?: string;
  contentType?: string;
}

export type FileControllerUploadFilesBodyFolder =
  (typeof FileControllerUploadFilesBodyFolder)[keyof typeof FileControllerUploadFilesBodyFolder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileControllerUploadFilesBodyFolder = {
  properties: 'properties',
  users: 'users',
  tenancies: 'tenancies',
  payments: 'payments',
} as const;

export type FileControllerUploadFilesBodySub =
  (typeof FileControllerUploadFilesBodySub)[keyof typeof FileControllerUploadFilesBodySub];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileControllerUploadFilesBodySub = {
  images: 'images',
  documents: 'documents',
  profile: 'profile',
  identity: 'identity',
  agreements: 'agreements',
  inspections: 'inspections',
  proof: 'proof',
} as const;

export type FileControllerUploadFilesBody = {
  files: Blob[];
  folder: FileControllerUploadFilesBodyFolder;
  sub: FileControllerUploadFilesBodySub;
  tenantId: string;
  /** @nullable */
  propertyId?: string | null;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  tenancyId?: string | null;
  /** @nullable */
  paymentId?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  contentType?: string | null;
};

export type FileControllerUploadFileBodyFolder =
  (typeof FileControllerUploadFileBodyFolder)[keyof typeof FileControllerUploadFileBodyFolder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileControllerUploadFileBodyFolder = {
  properties: 'properties',
  users: 'users',
  tenancies: 'tenancies',
  payments: 'payments',
} as const;

export type FileControllerUploadFileBodySub =
  (typeof FileControllerUploadFileBodySub)[keyof typeof FileControllerUploadFileBodySub];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileControllerUploadFileBodySub = {
  images: 'images',
  documents: 'documents',
  profile: 'profile',
  identity: 'identity',
  agreements: 'agreements',
  inspections: 'inspections',
  proof: 'proof',
} as const;

export type FileControllerUploadFileBody = {
  file: Blob;
  folder: FileControllerUploadFileBodyFolder;
  sub: FileControllerUploadFileBodySub;
  tenantId: string;
  /** @nullable */
  propertyId?: string | null;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  tenancyId?: string | null;
  /** @nullable */
  paymentId?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  contentType?: string | null;
};

export type FileControllerListFilesParams = {
  prefix: string;
};

export const getDomio = () => {
  const authControllerGetUsers = () => {
    return customInstanceMutator<null>({ url: `/auth`, method: 'GET' });
  };

  const authControllerLogin = (signInData: SignInData) => {
    return customInstanceMutator<AuthToken>({
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signInData,
    });
  };

  const authControllerSignup = (signupDto: SignupDto) => {
    return customInstanceMutator<AuthToken>({
      url: `/auth/signup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signupDto,
    });
  };

  const authControllerGetProfile = () => {
    return customInstanceMutator<GetSessionAndUserResult>({
      url: `/auth/profile`,
      method: 'GET',
    });
  };

  const authControllerGetUserId = () => {
    return customInstanceMutator<string>({
      url: `/auth/get-id`,
      method: 'GET',
    });
  };

  const propertyControllerCreate = (createPropertyDto: CreatePropertyDto) => {
    return customInstanceMutator<CreatePropertyDto[]>({
      url: `/property`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPropertyDto,
    });
  };

  const propertyControllerUpdateProperty = (
    updatePropertyDto: UpdatePropertyDto,
  ) => {
    return customInstanceMutator<UpdatePropertyResult>({
      url: `/property/update`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updatePropertyDto,
    });
  };

  const propertyControllerGet = (id: string) => {
    return customInstanceMutator<null>({
      url: `/property/${id}`,
      method: 'GET',
    });
  };

  const propertyControllerGetByOwner = (ownerId: string) => {
    return customInstanceMutator<PropertyResult[]>({
      url: `/property/owner/${ownerId}`,
      method: 'GET',
    });
  };

  const propertyControllerGetOwnerStats = (ownerId: string) => {
    return customInstanceMutator<PropertyStatsResult>({
      url: `/property/owner/stats/${ownerId}`,
      method: 'GET',
    });
  };

  const fileControllerUploadFiles = (
    fileControllerUploadFilesBody: FileControllerUploadFilesBody,
  ) => {
    const formData = new FormData();
    fileControllerUploadFilesBody.files.forEach((value) =>
      formData.append(`files`, value),
    );
    formData.append(`folder`, fileControllerUploadFilesBody.folder);
    formData.append(`sub`, fileControllerUploadFilesBody.sub);
    formData.append(`tenantId`, fileControllerUploadFilesBody.tenantId);
    if (
      fileControllerUploadFilesBody.propertyId !== undefined &&
      fileControllerUploadFilesBody.propertyId !== null
    ) {
      formData.append(`propertyId`, fileControllerUploadFilesBody.propertyId);
    }
    if (
      fileControllerUploadFilesBody.userId !== undefined &&
      fileControllerUploadFilesBody.userId !== null
    ) {
      formData.append(`userId`, fileControllerUploadFilesBody.userId);
    }
    if (
      fileControllerUploadFilesBody.tenancyId !== undefined &&
      fileControllerUploadFilesBody.tenancyId !== null
    ) {
      formData.append(`tenancyId`, fileControllerUploadFilesBody.tenancyId);
    }
    if (
      fileControllerUploadFilesBody.paymentId !== undefined &&
      fileControllerUploadFilesBody.paymentId !== null
    ) {
      formData.append(`paymentId`, fileControllerUploadFilesBody.paymentId);
    }
    if (
      fileControllerUploadFilesBody.fileName !== undefined &&
      fileControllerUploadFilesBody.fileName !== null
    ) {
      formData.append(`fileName`, fileControllerUploadFilesBody.fileName);
    }
    if (
      fileControllerUploadFilesBody.contentType !== undefined &&
      fileControllerUploadFilesBody.contentType !== null
    ) {
      formData.append(`contentType`, fileControllerUploadFilesBody.contentType);
    }

    return customInstanceMutator<null>({
      url: `/file/upload-files`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };

  const fileControllerUploadFile = (
    fileControllerUploadFileBody: FileControllerUploadFileBody,
  ) => {
    const formData = new FormData();
    formData.append(`file`, fileControllerUploadFileBody.file);
    formData.append(`folder`, fileControllerUploadFileBody.folder);
    formData.append(`sub`, fileControllerUploadFileBody.sub);
    formData.append(`tenantId`, fileControllerUploadFileBody.tenantId);
    if (
      fileControllerUploadFileBody.propertyId !== undefined &&
      fileControllerUploadFileBody.propertyId !== null
    ) {
      formData.append(`propertyId`, fileControllerUploadFileBody.propertyId);
    }
    if (
      fileControllerUploadFileBody.userId !== undefined &&
      fileControllerUploadFileBody.userId !== null
    ) {
      formData.append(`userId`, fileControllerUploadFileBody.userId);
    }
    if (
      fileControllerUploadFileBody.tenancyId !== undefined &&
      fileControllerUploadFileBody.tenancyId !== null
    ) {
      formData.append(`tenancyId`, fileControllerUploadFileBody.tenancyId);
    }
    if (
      fileControllerUploadFileBody.paymentId !== undefined &&
      fileControllerUploadFileBody.paymentId !== null
    ) {
      formData.append(`paymentId`, fileControllerUploadFileBody.paymentId);
    }
    if (
      fileControllerUploadFileBody.fileName !== undefined &&
      fileControllerUploadFileBody.fileName !== null
    ) {
      formData.append(`fileName`, fileControllerUploadFileBody.fileName);
    }
    if (
      fileControllerUploadFileBody.contentType !== undefined &&
      fileControllerUploadFileBody.contentType !== null
    ) {
      formData.append(`contentType`, fileControllerUploadFileBody.contentType);
    }

    return customInstanceMutator<null>({
      url: `/file/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };

  const fileControllerGenerateUploadUrl = (uploadFileDto: UploadFileDto) => {
    return customInstanceMutator<null>({
      url: `/file/upload-url`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: uploadFileDto,
    });
  };

  const fileControllerGetDownloadUrl = (key: string) => {
    return customInstanceMutator<null>({
      url: `/file/download/${key}`,
      method: 'GET',
    });
  };

  const fileControllerListFiles = (params: FileControllerListFilesParams) => {
    return customInstanceMutator<null>({
      url: `/file/list`,
      method: 'GET',
      params,
    });
  };

  const fileControllerDeleteFile = (key: string) => {
    return customInstanceMutator<null>({
      url: `/file/delete/${key}`,
      method: 'DELETE',
    });
  };

  return {
    authControllerGetUsers,
    authControllerLogin,
    authControllerSignup,
    authControllerGetProfile,
    authControllerGetUserId,
    propertyControllerCreate,
    propertyControllerUpdateProperty,
    propertyControllerGet,
    propertyControllerGetByOwner,
    propertyControllerGetOwnerStats,
    fileControllerUploadFiles,
    fileControllerUploadFile,
    fileControllerGenerateUploadUrl,
    fileControllerGetDownloadUrl,
    fileControllerListFiles,
    fileControllerDeleteFile,
  };
};
export type AuthControllerGetUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['authControllerGetUsers']>>
>;
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['authControllerLogin']>>
>;
export type AuthControllerSignupResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['authControllerSignup']>>
>;
export type AuthControllerGetProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['authControllerGetProfile']>>
>;
export type AuthControllerGetUserIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['authControllerGetUserId']>>
>;
export type PropertyControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['propertyControllerCreate']>>
>;
export type PropertyControllerUpdatePropertyResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDomio>['propertyControllerUpdateProperty']>
  >
>;
export type PropertyControllerGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['propertyControllerGet']>>
>;
export type PropertyControllerGetByOwnerResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDomio>['propertyControllerGetByOwner']>
  >
>;
export type PropertyControllerGetOwnerStatsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDomio>['propertyControllerGetOwnerStats']>
  >
>;
export type FileControllerUploadFilesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['fileControllerUploadFiles']>>
>;
export type FileControllerUploadFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['fileControllerUploadFile']>>
>;
export type FileControllerGenerateUploadUrlResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDomio>['fileControllerGenerateUploadUrl']>
  >
>;
export type FileControllerGetDownloadUrlResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDomio>['fileControllerGetDownloadUrl']>
  >
>;
export type FileControllerListFilesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['fileControllerListFiles']>>
>;
export type FileControllerDeleteFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDomio>['fileControllerDeleteFile']>>
>;
