/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Domio
 * The domio property application
 * OpenAPI spec version: 1.0
 */
export interface SignInData {
  email: string;
  password: string;
}

export interface SignupDto { [key: string]: unknown }

